apiVersion: batch/v1
kind: Job
metadata:
  name: kraken-pod
spec:
  selector: {}
  template:
    metadata:
      name: kraken
    spec:
      serviceAccountName: useroot
      volumes:
      - name: config
        configMap:
          name: kube-config
      containers:
        - name: kraken-runtime
          serviceAccount: useroot
          image: quay.io/chaos-kubox/krkn-hub:pod-scenarios
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              value: openshift-etcd
            - name: POD_LABEL
              value: "app=etcd"
            - name: DISRUPTION_COUNT
              value: "1"
            - name: EXPECTED_POD_COUNT
              value: "3"
            - name: CERBERUS_ENABLED
              value: "False"
          volumeMounts:
            - name: config
              mountPath: /root/.kube
          securityContext:
            privileged: true
      restartPolicy: Never
