---
- hosts: local
  gather_facts: true
  tasks:
  - name: Run container
    containers.podman.podman_container:
      name: cerberus
      image: quay.io/openshift-scale/cerberus:kraken-hub
      state: started
      restart: no
      recreate: no
      network: host
      detach: yes
      volume:
        - /root/.kube/config:/root/.kube/config
      privileged: true
      env_host: true
#      rm: true

